pipeline {
    agent {
        label 'AGENT-1'
    }
    environment { 
        appVersion = ''
        REGION     = "us-east-1"
        ACC_ID     = "127492125014"
        PROJECT    = "roboshop"
    }

    /* options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }

    parameters {
        booleanParam(name: 'deploy', defaultValue: false, description: 'Toggle this value')
    } */

    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: env.REGION) {
                        sh """
                           cd 00-vpc
                           terraform init -reconfigure
                        """
                    }
                }
            }
        }
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            echo 'Hello Failure'
        }
    }
}
