pipeline {
    agent {
        label 'AGENT-1'
    }
    environment { 
        appVersion = ''
        REGION     = "us-east-1"
        ACC_ID     = "127492125014"
        PROJECT    = "roboshop"
    }

    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')   // enables colored logs
    }

    // parameters {
    //     booleanParam(name: 'deploy', defaultValue: false, description: 'Toggle this value')
    // }

    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: env.REGION) {
                        sh """
                           cd 20-bastion
                           terraform init -reconfigure
                        """
                    }
                }
            }
        }

        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: env.REGION) {
                        sh """
                           cd 20-bastion
                           terraform plan
                        """
                    }
                }
            }
        }
        stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: env.REGION) {
                        sh """
                           cd 20-bastion
                           terraform apply -auto-approve
                        """
                    }
                }
            }
        }

    }

    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            echo 'Hello Failure'
        }
    }
}
